---
- name: Clean any previous VDDK
  file:
    path: "{{ v2v_vddk_install_dir }}/vmware-vix-disklib-distrib/"
    state: absent
    
- name: Create directory for VDDK
  file:
    path: "{{ v2v_vddk_install_dir }}"
    state: directory
    mode: 0755

- name: Download the VDDK if a URL has been provided
  get_url:
    url: "{{ v2v_vddk_package_url }}"
    dest: "/tmp/{{ v2v_vddk_package_name }}"
    mode: 0600

- name: Extract VDDK
  unarchive:
    src: "/tmp/{{ v2v_vddk_package_name }}"
    dest: "{{ v2v_vddk_install_dir }}"
    remote_src: true

- name: Remove downloaded file
  file:
    path: "/tmp/{{ v2v_vddk_package_name }}"
    state: absent
